Data = {}
Data.getState = function (country) {
    var states = []
    states["US"] = [
        { label: "West Virginia", value: "WV" },
        { label: "Wyoming", value: "WY" },
        { label: "Vermont", value: "VT" },
        { label: "Washington", value: "WA" },
        { label: "Wisconsin", value: "WI" },
        { label: "Texas", value: "TX" },
        { label: "Utah", value: "UT" },
        { label: "Virginia", value: "VA" },
        { label: "South Carolina", value: "SC" },
        { label: "South Dakota", value: "SD" },
        { label: "Tennessee", value: "TN" },
        { label: "Oklahoma", value: "OK" },
        { label: "Oregon", value: "OR" },
        { label: "Pennsylvania", value: "PA" },
        { label: "Nevada", value: "NV" },
        { label: "New York", value: "NY" },
        { label: "Ohio", value: "OH" },
        { label: "New Hampshire", value: "NH" },
        { label: "New Jersey", value: "NJ" },
        { label: "New Mexico", value: "NM" },
        { label: "North Carolina", value: "NC" },
        { label: "North Dakota", value: "ND" },
        { label: "Nebraska", value: "NE" },
        { label: "Missouri", value: "MO" },
        { label: "Mississippi", value: "MS" },
        { label: "Montana", value: "MT" },
        { label: "Maine", value: "ME" },
        { label: "Michigan", value: "MI" },
        { label: "Minnesota", value: "MN" },
        { label: "Louisiana", value: "LA" },
        { label: "Massachusetts", value: "MA" },
        { label: "Maryland", value: "MD" },
        { label: "Indiana", value: "IN" },
        { label: "Kansas", value: "KS" },
        { label: "Kentucky", value: "KY" },
        { label: "Iowa", value: "IA" },
        { label: "Idaho", value: "ID" },
        { label: "Illinois", value: "IL" },
        { label: "Florida", value: "FL" },
        { label: "Georgia", value: "GA" },
        { label: "Hawaii", value: "HI" },
        { label: "Connecticut", value: "CT" },
        { label: "District of Columbia", value: "DC" },
        { label: "Delaware", value: "DE" },
        { label: "Arizona", value: "AZ" },
        { label: "California", value: "CA" },
        { label: "Colorado", value: "CO" },
        { label: "Alaska", value: "AK" },
        { label: "Alabama", value: "AL" },
        { label: "Arkansas", value: "AR" },
        { label: "Rhode Island", value: "RI" }
    ]
    states["AR"] = [
        { label: "Buenos Aires", value: "BA" },
        { label: "Catamarca", value: "CA" },
        { label: "Chubut", value: "CB" },
        { label: "Cordoba", value: "CR" },
        { label: "Chaco", value: "CH" },
        { label: "Formosa", value: "FO" },
        { label: "La Rioja", value: "LR" },
        { label: "Mendoza", value: "MD" },
        { label: "Misiones", value: "VA" },
        { label: "Neuquen", value: "NE" },
        { label: "Jujuy", value: "N" },
        { label: "Rio Negro", value: "RN" },
        { label: "Salta", value: "SA" },
        { label: "Santa Cruz", value: "SC" },
        { label: "Santiago del Estero", value: "SE" },
        { label: "Santa Fe", value: "SF" },
        { label: "San Juan", value: "SJ" },
        { label: "San Luis", value: "SL" },
        { label: "Tucuman", value: "TU" }
    ]
    states["AU"] = [
        { label: "Australian Capital Territory", value: "AC" },
        { label: "New South Wales", value: "NS" },
        { label: "Northern Territory", value: "NT" },
        { label: "Queensland", value: "QL" },
        { label: "South Australia", value: "SA" },
        { label: "Tasmania", value: "TS" },
        { label: "Victoria", value: "VI" },
        { label: "Western Australia", value: "WA" }
    ]
    states["BR"] = [
        { label: "Acre", value: "AC" },
        { label: "Alagoas", value: "AL" },
        { label: "Amazonas", value: "AM" },
        { label: "Amapa", value: "AP" },
        { label: "Bahia", value: "BA" },
        { label: "Ceara", value: "CE" },
        { label: "Distrito Federal", value: "DF" },
        { label: "Espirito Santo", value: "ES" },
        { label: "Fernando de Noronha", value: "FN" },
        { label: "Goias", value: "GO" },
        { label: "Maranhao", value: "MA" },
        { label: "Minas Gerais", value: "MG" },
        { label: "Mato Grosso do Sul", value: "MS" },
        { label: "Mato Grosso", value: "MT" },
        { label: "Para", value: "PA" },
        { label: "Paraiba", value: "PB" },
        { label: "Pernambuco", value: "PE" },
        { label: "Piaui", value: "PI" },
        { label: "Parana", value: "PR" },
        { label: "Rio de Janeiro", value: "RJ" },
        { label: "Rio Grande do Norte", value: "RN" },
        { label: "Rondonia", value: "RO" },
        { label: "Roraima", value: "RR" },
        { label: "Rio Grande do Sul", value: "RS" },
        { label: "Santa Catarina", value: "SC" },
        { label: "Sergipe", value: "SE" },
        { label: "Sao Paulo", value: "SP" },
        { label: "Tocantins", value: "TO" }
    ]
    states["CA"] = [
        { label: "Alberta", value: "AB" },
        { label: "British Columbia", value: "BC" },
        { label: "Manitoba", value: "MB" },
        { label: "New Brunswick", value: "NB" },
        { label: "Nova Scotia", value: "NS" },
        { label: "Northwest Territories", value: "NT" },
        { label: "Nunavut", value: "NU" },
        { label: "Ontario", value: "ON" },
        { label: "Prince Edward Island", value: "PE" },
        { label: "Quebec", value: "QC" },
        { label: "Saskatchewan", value: "SK" },
        { label: "Yukon Territory", value: "YT" },
        { label: "Newfoundland and Labrador", value: "NL" }
    ]
    states["CO"] = [
        { label: "Amazonas", value: "Azo" },
        { label: "Antioquia", value: "Ant" },
        { label: "Arauca", value: "Aru" },
        { label: "Atlantico", value: "Aca" },
        { label: "Cundinamarca", value: "Cdi" }
    ]
    states["VE"] = [
        { label: "Miranda", value: "MIR" },
    ]
    states["MX"] = [
        { value: 'AG', label: "Aguascalientes" },
        { value: 'BC', label: "Baja California" },
        { value: 'BS', label: "Baja California Sur" },
        { value: 'CM', label: "Campeche" },
        { value: "CO", label: "Coahuila" },
        { value: "CL", label: "Colima" },
        { value: "CS", label: "Chiapas" },
        { value: "CH", label: "Chihuahua" },
        { value: "CX", label: "Ciudad de México" },
        { value: "DG", label: "Durango" },
        { value: "GT", label: "Guanajuato" },
        { value: "GR", label: "Guerrero" },
        { value: "HG", label: "Hidalgo" },
        { value: "JC", label: "Jalisco" },
        { value: "EM", label: "México" },
        { value: "MI", label: "Michoacán" },
        { value: "MO", label: "Morelos" },
        { value: "NA", label: "Nayarit" },
        { value: "NL", label: "Nuevo León" },
        { value: "OA", label: "Oaxaca" },
        { value: "PU", label: "Puebla" },
        { value: "QT", label: "Querétaro" },
        { value: "QR", label: "Quintana Roo" },
        { value: "SL", label: "San Luis Potosí" },
        { value: "SI", label: "Sinaloa" },
        { value: "SO", label: "Sonora" },
        { value: "TB", label: "Tabasco" },
        { value: "TM", label: "Tamaulipas" },
        { value: "TL", label: "Tlaxcala" },
        { value: "VE", label: "Veracruz" },
        { value: "YU", label: "Yucatán" },
        { value: "ZA", label: "Zacatecas" }
    ]
    return states[country]
}

Data.getCountries = function () {
    return [
        { label: "Afghanistan", value: "AF" },
        { label: "Albania", value: "AL" },
        { label: "Algeria", value: "DZ" },
        { label: "American Samoa", value: "AS" },
        { label: "Andorra", value: "AD" },
        { label: "Angola", value: "AO" },
        { label: "Anguilla", value: "AI" },
        { label: "Antarctica", value: "AQ" },
        { label: "Antigua And Barbuda", value: "AG" },
        { label: "Argentina", value: "AR" },
        { label: "Armenia", value: "AM" },
        { label: "Aruba", value: "AW" },
        { label: "Australia", value: "AU" },
        { label: "Austria", value: "AT" },
        { label: "Azerbaijan", value: "AZ" },
        { label: "Bahamas", value: "BS" },
        { label: "Bahrain", value: "BH" },
        { label: "Bangladesh", value: "BD" },
        { label: "Barbados", value: "BB" },
        { label: "Belarus", value: "BY" },
        { label: "Belgium", value: "BE" },
        { label: "Belize", value: "BZ" },
        { label: "Benin", value: "BJ" },
        { label: "Bermuda", value: "BM" },
        { label: "Bhutan", value: "BT" },
        { label: "Bolivia", value: "BO" },
        { label: "Bosnia And Herzegovina", value: "BA" },
        { label: "Botswana", value: "BW" },
        { label: "Bouvet Island", value: "BV" },
        { label: "Brazil", value: "BR" },
        { label: "British Indian Ocean Territory", value: "IO" },
        { label: "British Virgin Islands", value: "VG" },
        { label: "Brunei Darussalam", value: "BN" },
        { label: "Bulgaria", value: "BG" },
        { label: "Burkina Faso", value: "BF" },
        { label: "Burundi", value: "BI" },
        { label: "Cambodia", value: "KH" },
        { label: "Cameroon", value: "CM" },
        { label: "Canada", value: "CA" },
        { label: "Cape Verde", value: "CV" },
        { label: "Cayman Islands", value: "KY" },
        { label: "Central African Republic", value: "CF" },
        { label: "Chad", value: "TD" },
        { label: "Chile", value: "CL" },
        { label: "China", value: "CN" },
        { label: "Christmas Island", value: "CX" },
        { label: "Cocos (Keeling) Islands", value: "CC" },
        { label: "Colombia", value: "CO" },
        { label: "Comoros", value: "KM" },
        { label: "Congo", value: "CG" },
        { label: "Congo, Democratic Republic Of The", value: "CD" },
        { label: "Cook Islands", value: "CK" },
        { label: "Costa Rica", value: "CR" },
        { label: "Cote d'Ivoire", value: "CI" },
        { label: "Croatia", value: "HR" },
        { label: "Cuba", value: "CU" },
        { label: "Cyprus", value: "CY" },
        { label: "Czech Republic", value: "CZ" },
        { label: "Denmark", value: "DK" },
        { label: "Djibouti", value: "DJ" },
        { label: "Dominica", value: "DM" },
        { label: "Dominican Republic", value: "DO" },
        { label: "East Timor", value: "TP" },
        { label: "Ecuador", value: "EC" },
        { label: "Egypt", value: "EG" },
        { label: "El Salvador", value: "SV" },
        { label: "Equatorial Guinea", value: "GQ" },
        { label: "Eritrea", value: "ER" },
        { label: "Estonia", value: "EE" },
        { label: "Ethiopia", value: "ET" },
        { label: "Falkland Islands", value: "FK" },
        { label: "Faroe Islands", value: "FO" },
        { label: "Fiji", value: "FJ" },
        { label: "Finland", value: "FI" },
        { label: "France", value: "FR" },
        { label: "French Guiana", value: "GF" },
        { label: "French Polynesia", value: "PF" },
        { label: "French Southern Territories", value: "TF" },
        { label: "Gabon", value: "GA" },
        { label: "Gambia", value: "GM" },
        { label: "Georgia", value: "GE" },
        { label: "Germany", value: "DE" },
        { label: "Ghana", value: "GH" },
        { label: "Gibraltar", value: "GI" },
        { label: "Greece", value: "GR" },
        { label: "Greenland", value: "GL" },
        { label: "Grenada", value: "GD" },
        { label: "Guadeloupe", value: "GP" },
        { label: "Guam", value: "GU" },
        { label: "Guatemala", value: "GT" },
        { label: "Guinea", value: "GN" },
        { label: "Guinea-Bissau", value: "GW" },
        { label: "Guyana", value: "GY" },
        { label: "Haiti", value: "HT" },
        { label: "Heard And Mcdonald Islands", value: "HM" },
        { label: "Honduras", value: "HN" },
        { label: "Hong Kong SAR", value: "HK" },
        { label: "Hungary", value: "HU" },
        { label: "Iceland", value: "IS" },
        { label: "India", value: "IN" },
        { label: "Indonesia", value: "ID" },
        { label: "Iran", value: "IR" },
        { label: "Iraq", value: "IQ" },
        { label: "Ireland", value: "IE" },
        { label: "Israel", value: "IL" },
        { label: "Italy", value: "IT" },
        { label: "Jamaica", value: "JM" },
        { label: "Japan", value: "JP" },
        { label: "Jordan", value: "JO" },
        { label: "Kazakhstan", value: "KZ" },
        { label: "Kenya", value: "KE" },
        { label: "Kiribati", value: "KI" },
        { label: "Korea, Democratic PeopleS Republic Of", value: "KP" },
        { label: "Korea, Republic Of", value: "KR" },
        { label: "Kuwait", value: "KW" },
        { label: "Kyrgyzstan", value: "KG" },
        { label: "Lao People'S Democratic Republic", value: "LA" },
        { label: "Latvia", value: "LV" },
        { label: "Lebanon", value: "LB" },
        { label: "Lesotho", value: "LS" },
        { label: "Liberia", value: "LR" },
        { label: "Libyan Arab Jamahiriya", value: "LY" },
        { label: "Liechtenstein", value: "LI" },
        { label: "Lithuania", value: "LT" },
        { label: "Luxembourg", value: "LU" },
        { label: "Macau (San), China", value: "MO" },
        { label: "Macedonia (Fyrom)", value: "MK" },
        { label: "Madagascar", value: "MG" },
        { label: "Malawi", value: "MW" },
        { label: "Malaysia", value: "MY" },
        { label: "Maldives", value: "MV" },
        { label: "Mali", value: "ML" },
        { label: "Malta", value: "MT" },
        { label: "Marshall Islands", value: "MH" },
        { label: "Martinique", value: "MQ" },
        { label: "Mauritania", value: "MR" },
        { label: "Mauritius", value: "MU" },
        { label: "Mayotte", value: "YT" },
        { label: "Mexico", value: "MX" },
        { label: "Micronesia", value: "FM" },
        { label: "Moldova, Republic Of", value: "MD" },
        { label: "Monaco", value: "MC" },
        { label: "Mongolia", value: "MN" },
        { label: "Montenegro", value: "ME" },
        { label: "Montserrat", value: "MS" },
        { label: "Morocco", value: "MA" },
        { label: "Mozambique", value: "MZ" },
        { label: "Myanmar", value: "MM" },
        { label: "Namibia", value: "NA" },
        { label: "Nauru", value: "NR" },
        { label: "Nepal", value: "NP" },
        { label: "Netherlands Antilles", value: "AN" },
        { label: "Netherlands", value: "NL" },
        { label: "New Caledonia", value: "NC" },
        { label: "New Zealand", value: "NZ" },
        { label: "Nicaragua", value: "NI" },
        { label: "Niger", value: "NE" },
        { label: "Nigeria", value: "NG" },
        { label: "Niue", value: "NU" },
        { label: "Norfolk Island", value: "NF" },
        { label: "Northern Ireland", value: "ND" },
        { label: "Northern Mariana Islands", value: "MP" },
        { label: "Norway", value: "NO" },
        { label: "Oman", value: "OM" },
        { label: "Pakistan", value: "PK" },
        { label: "Palau", value: "PW" },
        { label: "Panama", value: "PA" },
        { label: "Papua New Guinea", value: "PG" },
        { label: "Paraguay", value: "PY" },
        { label: "Peru", value: "PE" },
        { label: "Philippines", value: "PH" },
        { label: "Pitcairn Island", value: "PN" },
        { label: "Poland", value: "PL" },
        { label: "Portugal", value: "PT" },
        { label: "Puerto Rico", value: "PR" },
        { label: "Qatar", value: "QA" },
        { label: "Reunion", value: "RE" },
        { label: "Romania", value: "RO" },
        { label: "Russian Federation", value: "RU" },
        { label: "Rwanda", value: "RW" },
        { label: "Saint Barthelemy", value: "BL" },
        { label: "Saint Helena", value: "SH" },
        { label: "Saint Kitts And Nevis", value: "KN" },
        { label: "Saint Lucia", value: "LC" },
        { label: "Saint Martin", value: "MF" },
        { label: "Saint Pierre And Miquelon", value: "PM" },
        { label: "Saint Vincent And The Grenadines", value: "VC" },
        { label: "Samoa", value: "WS" },
        { label: "San Marino", value: "SM" },
        { label: "Sao Tome And Principe", value: "ST" },
        { label: "Saudi Arabia", value: "SA" },
        { label: "Senegal", value: "SN" },
        { label: "Serbia", value: "RS" },
        { label: "Seychelles", value: "SC" },
        { label: "Sierra Leone", value: "SL" },
        { label: "Singapore", value: "SG" },
        { label: "Sint Maarten", value: "NM" },
        { label: "Slovakia", value: "SK" },
        { label: "Slovenia", value: "SI" },
        { label: "Solomon Islands", value: "SB" },
        { label: "Somalia", value: "SO" },
        { label: "South Africa", value: "ZA" },
        { label: "South Georgia And The South Sandwich Islands", value: "GS" },
        { label: "Spain", value: "ES" },
        { label: "Sri Lanka", value: "LK" },
        { label: "Sudan", value: "SD" },
        { label: "Suriname", value: "SR" },
        { label: "Svalbard & Jan Mayen Island", value: "SJ" },
        { label: "Swaziland", value: "SZ" },
        { label: "Sweden", value: "SE" },
        { label: "Switzerland", value: "CH" },
        { label: "Syrian Arab Republic", value: "SY" },
        { label: "Taiwan", value: "TW" },
        { label: "Tajikistan", value: "TJ" },
        { label: "Tanzania, United Republic Of", value: "TZ" },
        { label: "Thailand", value: "TH" },
        { label: "Togo", value: "TG" },
        { label: "Tokelau", value: "TK" },
        { label: "Tonga", value: "TO" },
        { label: "Trinidad And Tobago", value: "TT" },
        { label: "Tunisia", value: "TN" },
        { label: "Turkey", value: "TR" },
        { label: "Turkmenistan", value: "TM" },
        { label: "Turks And Caicos Islands", value: "TC" },
        { label: "Tuvalu", value: "TV" },
        { label: "U.S. Virgin Islands", value: "VI" },
        { label: "Uganda", value: "UG" },
        { label: "Ukraine", value: "UA" },
        { label: "United Arab Emirates", value: "AE" },
        { label: "United Kingdom", value: "GB" },
        { label: "Uruguay", value: "UY" },
        { label: "Us Minor Outlying Islands", value: "UM" },
        { label: "USA", value: "US" },
        { label: "Uzbekistan", value: "UZ" },
        { label: "Vanuatu", value: "VU" },
        { label: "Vatican City State", value: "VA" },
        { label: "Venezuela", value: "VE" },
        { label: "Vietnam", value: "VN" },
        { label: "Wallis And Futuna Islands", value: "WF" },
        { label: "Western Sahara", value: "EH" },
        { label: "Yemen, Republic Of", value: "YE" },
        { label: "Zambia", value: "ZM" },
        { label: "Zimbabwe", value: "ZW" }
    ]
}

Data.getEmployeeType = function () {
    return [
        { label: 'Manager', value: 'MNG' },
        { label: 'Capture', value: 'CPT' },
        { label: 'Supervisor', value: 'SPR' },
    ]
}

Data.getBanks = function () {
    return [
        { label: 'CITI BANAMEX', value: 'CITI BANAMEX' },
        { label: 'BANCOMEXT', value: 'BANCOMEXT' },
        { label: 'BANOBRAS', value: 'BANOBRAS' },
        { label: 'BBVA BANCOMER', value: 'BBVA BANCOMER' },
        { label: 'SANTANDER', value: 'SANTANDER' },
        { label: 'BANJERCITO', value: 'BANJERCITO' },
        { label: 'HSBC', value: 'HSBC' },
        { label: 'BAJIO', value: 'BAJIO' },
        { label: 'IXE', value: 'IXE' },
        { label: 'INBURSA', value: 'INBURSA' },
        { label: 'INTERACCIONES', value: 'INTERACCIONES' },
        { label: 'MIFEL', value: 'MIFEL' },
        { label: 'SCOTIABANK', value: 'SCOTIABANK' },
        { label: 'BANREGIO', value: 'BANREGIO' },
        { label: 'INVEX', value: 'INVEX' },
        { label: 'BANSI', value: 'BANSI' },
        { label: 'AFIRME', value: 'AFIRME' },
        { label: 'BANORTE', value: 'BANORTE' },
        { label: 'THE ROYAL BANK', value: 'THE ROYAL BANK' },
        { label: 'AMERICAN EXPRESS', value: 'AMERICAN EXPRESS' },
        { label: 'BAMSA', value: 'BAMSA' },
        { label: 'TOKYO', value: 'TOKYO' },
        { label: 'JP MORGAN', value: 'JP MORGAN' },
        { label: 'BMONEX', value: 'BMONEX' },
        { label: 'VE POR MAS', value: 'VE POR MAS' },
        { label: 'ING', value: 'ING' },
        { label: 'DEUTSCHE', value: 'DEUTSCHE' },
        { label: 'CREDIT SUISSE', value: 'CREDIT SUISSE' },
        { label: 'AZTECA', value: 'AZTECA' },
        { label: 'AUTOFIN', value: 'AUTOFIN' },
        { label: 'BARCLAYS', value: 'BARCLAYS' },
        { label: 'COMPARTAMOS', value: 'COMPARTAMOS' },
        { label: 'BANCO FAMSA', value: 'BANCO FAMSA' },
        { label: 'BMULTIVA', value: 'BMULTIVA' },
        { label: 'ACTINVER', value: 'ACTINVER' },
        { label: 'WAL-MART', value: 'WAL-MART' },
        { label: 'NAFIN', value: 'NAFIN' },
        { label: 'INTERBANCO', value: 'INTERBANCO' },
        { label: 'BANCOPPEL', value: 'BANCOPPEL' },
        { label: 'ABC CAPITAL', value: 'ABC CAPITAL' },
        { label: 'UBS BANK', value: 'UBS BANK' },
        { label: 'CONSUBANCO', value: 'CONSUBANCO' },
        { label: 'VOLKSWAGEN', value: 'VOLKSWAGEN' },
        { label: 'CIBANCO', value: 'CIBANCO' },
        { label: 'BBASE', value: 'BBASE' },
        { label: 'BANSEFI', value: 'BANSEFI' },
        { label: 'HIPOTECARIA FEDERAL', value: 'HIPOTECARIA FEDERAL' },
        { label: 'MONEXCB', value: 'MONEXCB' },
        { label: 'GBM', value: 'GBM' },
        { label: 'MASARI', value: 'MASARI' },
        { label: 'ESTRUCTURADORES', value: 'ESTRUCTURADORES' },
        { label: 'VALUE', value: 'VALUE' },
        { label: 'TIBER', value: 'TIBER' },
        { label: 'VECTOR', value: 'VECTOR' },
        { label: 'B&B', value: 'B&B' },
        { label: 'ACCIVAL', value: 'ACCIVAL' },
        { label: 'MERRILL LYNCH', value: 'MERRILL LYNCH' },
        { label: 'FINAMEX', value: 'FINAMEX' },
        { label: 'VALMEX', value: 'VALMEX' },
        { label: 'UNICA', value: 'UNICA' },
        { label: 'MAPFRE', value: 'MAPFRE' },
        { label: 'PROFUTURO', value: 'PROFUTURO' },
        { label: 'CB ACTINVER', value: 'CB ACTINVER' },
        { label: 'OACTIN', value: 'OACTIN' },
        { label: 'SKANDIA VIDA', value: 'SKANDIA VIDA' },
        { label: 'CBDEUTSCHE', value: 'CBDEUTSCHE' },
        { label: 'ZURICH', value: 'ZURICH' },
        { label: 'ZURICHVI', value: 'ZURICHVI' },
        { label: 'SU CASITA', value: 'SU CASITA' },
        { label: 'CB INTERCAM', value: 'CB INTERCAM' },
        { label: 'CI BOLSA', value: 'CI BOLSA' },
        { label: 'BULLTICK CB', value: 'BULLTICK CB' },
        { label: 'STERLING', value: 'STERLING' },
        { label: 'FINCOMUN', value: 'FINCOMUN' },
        { label: 'HDI SEGUROS', value: 'HDI SEGUROS' },
        { label: 'ORDER', value: 'ORDER' },
        { label: 'AKALA', value: 'AKALA' },
        { label: 'CB JPMORGAN', value: 'CB JPMORGAN' },
        { label: 'REFORMA', value: 'REFORMA' },
        { label: 'STP', value: 'STP' },
        { label: 'TELECOMM', value: 'TELECOMM' },
        { label: 'EVERCORE', value: 'EVERCORE' },
        { label: 'SKANDIA FONDOS', value: 'SKANDIA FONDOS' },
        { label: 'SEGMTY', value: 'SEGMTY' },
        { label: 'ASEA', value: 'ASEA' },
        { label: 'KUSPIT', value: 'KUSPIT' },
        { label: 'SOFIEXPRESS', value: 'SOFIEXPRESS' },
        { label: 'UNAGRA', value: 'UNAGRA' },
        { label: 'OPCIONES EMPRESARIALES DEL NOROESTE', value: 'OPCIONES EMPRESARIALES DEL NOROESTE' },
        { label: 'CLS', value: 'CLS' },
        { label: 'INDEVAL', value: 'INDEVAL' },
        { label: 'LIBERTAD', value: 'LIBERTAD' },
    ]
}

Data.getCardTypes = function () {
    return [
        { label: 'Visa', value: 'visa' },
        { label: 'Mastercard', value: 'mastercard' },
        { label: 'American Express', value: 'american-express' },
        { label: 'Diners Club', value: 'diners-club' },
        { label: 'Discover', value: 'discover' },
        { label: 'JCB', value: 'jcb' },
        { label: 'UnionPay', value: 'unionpay' },
        { label: 'Maestro', value: 'maestro' },
        { label: 'Mir', value: 'mir' },
        { label: 'Elo', value: 'elo' },
        { label: 'Hiper', value: 'hiper' },
        { label: 'Hipercard', value: 'hipercard' },
    ]
}

export const getCountryByCode = function (code) {
    let country = ''
    let countries = Data.getCountries();
    for (let i = 0; i < countries.length; i++) {
        if (countries[i].value === code) {
            country = countries[i].label;
            break;
        }
    };
    return country
}

export const getStateByCode = function (country, stateCode) {
    let state = ''
    let states = Data.getState(country);
    if (states && states.length) {
        for (let i = 0; i < states.length; i++) {
            if (states[i].value === stateCode) {
                state = states[i].label;
                break;
            }
        };
    }
    return state
}